### ISSUE TITLE
html_report from config is not passed into args

### ISSUE THREAD

**Issue by HenleyKuang** [ArturSpirin/test_junkie#18]
1. Python version `python --version`
3.6.8
2. Test Junkie version `pip show test_junkie` 
Name: test-junkie
Version: 0.7a3
Summary: Modern Testing Framework
Home-page: https://www.test-junkie.com/
Author: Artur Spirin
Author-email: as.no.replies@gmail.com
License: UNKNOWN
Location: c:\serp_storage\.venv\lib\site-packages
Requires: colorama, configparser, statistics, psutil, appdirs, coverage
Required-by
3. Platform aka *_Windows 10_* or *_Linux Mint 18.1_* 
Windows 10
4. Command used, if running via terminal
tj run
5. Smallest code snippet that can reproduce the issue and /or description of the issue
```
Traceback (most recent call last):
  File "c:\serp_storage\.venv\lib\site-packages\test_junkie\cli\cli_runner.py", line 271, in run_suites
    quiet=args.quiet)
  File "c:\serp_storage\.venv\lib\site-packages\test_junkie\runner.py", line 193, in run
    self.__create_html_report(reporter)
  File "c:\serp_storage\.venv\lib\site-packages\test_junkie\runner.py", line 56, in __create_html_report
    reporter.generate_html_report(self.__kwargs.get("html_report"))
  File "c:\serp_storage\.venv\lib\site-packages\test_junkie\reporter\html_reporter.py", line 111, in generate_html_report
    with open(write_file, "w+") as output:
TypeError: expected str, bytes or os.PathLike object, not type
```

### Actual behaviour

---
*If attaching logs, make sure to remove any personal information, credentials, tokens, keys - anything that you don't
want to become public.*

**Comment by ArturSpirin** [comment]
@HenleyKuang Fix will be available in version 0.7a4
