### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by Rdvp1514** [ArturSpirin/test_junkie#39]
1. Python version `python --version` ----> Python 3.9.5
2. Test Junkie version `pip show test_junkie` ----> Version: 0.8a4

3. Platform aka *_Windows 10_* or *_Linux Mint 18.1_*  ----> Mac 11.2.3 
4. Command used, if running via terminal ----> N/a
5. Smallest code snippet that can reproduce the issue and /or description of the issue

When I'm trying to run in paralel (aggregator = runner.run(test_multithreading_limit=6, suite_multithreading_limit=2))
framework show an error that says
AttributeError: 'Thread' object has no attribute 'isAlive'

### Expected behavior
This famework should run all the test case in paralel 

### Actual behavior
open the browser but shows an error 

---
*If attaching logs, make sure to remove any personal information, credentials, tokens, keys - anything that you don't
want to become public.*
====== WebDriver manager ======
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ricardovalbuena/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/test_junkie/runner.py", line 308, in __run_suite
    while self.__processor.test_limit_reached():
  File "/Users/ricardovalbuena/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/test_junkie/parallels.py", line 87, in test_limit_reached
    if test["thread"].isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by Rdvp1514** [comment]
you should remove ON /lib/python3.9/site-packages/test_junkie/parallels.py line 87 .isAlive(), in order to work

**Comment by tirkarthi** [comment]
`isAlive` has been deprecated and removed in favor of `is_alive` in Python 3.9. Please use `is_alive` method present in both Python 2 and 3 to fix this.

**Comment by ArturSpirin** [comment]
Fixed
